spring.application.name=novaevents
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/novaevents
spring.datasource.username=root
spring.datasource.password=rootpass

spring.jpa.hibernate.ddl-auto=update
jwt.secret=novaevents-jwt-secret-key-for-hs256-signing
weather.api.key=94a9e6f5aecf85bcbe338656c34c3bfe